### PR TITLE
Updated Work Item Types to ADO Server 2020.1.1

### PR DESCRIPTION
**Pull request by omarv74**

### CODE REVIEW

**Comment by danhellem** [comment]
Thanks @omarv74 , will take a look soon

**Comment by danhellem** [comment]
@omarv74  i got access back, will take a look later this week

**Comment by omarv74** [comment]
@danhellem ,

Sounds good. Please let me know if anything else is needed. I have a sandbox environment ready.

**Comment by danhellem** [comment]
@omarv74  thank you for doing this

**Pull request merged**
